image: node:10.15-alpine


cache:
  paths:  
  - dist


stages:
    - build
    - publish


build:        
    stage: build    
    script:
        - npm ci
        - npm run dist                

npm_publish:        
    stage: publish
    only:
        - tags
    script:
        - "echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > ~/.npmrc"    
        - npm publish dist


    